services:
  - type: web
    name: pdf-to-excel-api
    env: docker
    plan: free
    region: oregon
    buildCommand: ""
    startCommand: ""
    autoDeploy: true
    envVars:
      - key: PORT
        value: 10000
